import { NextResponse } from 'next/server';
import { fyfAgentGraph } from '@/src/agents/graph';
import { createClient } from '@/src/infrastructure/db/server/supabase';
import { hashContent, isAuthFailure, requireWorkspaceAccess } from '@/src/infrastructure/db/server/auth';

export async function POST(request: Request) {
  try {
    const supabase = await createClient();
    const auth = await requireWorkspaceAccess(supabase, ['owner', 'editor']);

    if (isAuthFailure(auth)) {
      return auth.response;
    }

    const body = await request.json();
    const { topic, goal, format, tone } = body;

    if (!topic || !goal || !format || !tone) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    console.log("Invoking FYF Agent Graph with:", { topic, goal, format, tone });

    // Insert brief into database first
    const { data: briefData, error: briefError } = await supabase
      .from('content_briefs')
      .insert({
        workspace_id: auth.workspaceId,
        topic,
        business_goal: goal,
        format,
        angle: tone,
      })
      .select()
      .single();

    if (briefError) {
      console.error('Error inserting brief:', briefError);
      return NextResponse.json({ error: 'Failed to save brief' }, { status: 500 });
    }

    // Create a workflow run
    const { data: runData, error: runError } = await supabase
      .from('workflow_runs')
      .insert({
        workspace_id: auth.workspaceId,
        brief_id: briefData.id,
        status: 'DRAFTING'
      })
      .select()
      .single();

    if (runError) {
      console.error('Error inserting run:', runError);
      return NextResponse.json({ error: 'Failed to start workflow' }, { status: 500 });
    }

    // Map the incoming data to the actual state expected by src/agents/state.ts
    const initialState = {
      brief: {
        topic,
        businessGoal: goal,
        format,
        tone
      },
      messages: [],
      revisionCount: 0,
      status: 'initialized' as const
    };

    const finalState = await fyfAgentGraph.invoke(initialState);

    console.log("Graph execution finished. Revision count:", finalState.revisionCount);

    const draftContent = finalState.draftContent || "No content generated.";
    const contentHash = hashContent(draftContent);

    // Save the artifact
    const { data: artifactData, error: artifactError } = await supabase
      .from('content_artifacts')
      .insert({
        workspace_id: auth.workspaceId,
        workflow_run_id: runData.id,
        current_version: 1,
        content: draftContent
      })
      .select()
      .single();

    if (artifactError) {
      console.error('Error inserting artifact:', artifactError);
      return NextResponse.json({ error: 'Failed to save artifact' }, { status: 500 });
    }

    const { data: draftVersionData, error: draftVersionError } = await supabase
      .from('draft_versions')
      .insert({
        workspace_id: auth.workspaceId,
        workflow_run_id: runData.id,
        artifact_id: artifactData.id,
        version: 1,
        content: draftContent,
        content_hash: contentHash,
        reason: 'Initial Maker agent draft'
      })
      .select('version,content_hash')
      .single();

    if (draftVersionError) {
      console.error('Error inserting draft version:', draftVersionError);
      return NextResponse.json({ error: 'Failed to save draft version' }, { status: 500 });
    }

    // Update the run status to review
    await supabase
      .from('workflow_runs')
      .update({
        status: finalState.status === 'ready_for_human' ? 'NEEDS_HUMAN_REVIEW' : 'NEEDS_ATTENTION',
        revision_count: finalState.revisionCount || 0
      })
      .eq('id', runData.id);

    return NextResponse.json({
      success: true,
      data: {
        briefId: briefData.id,
        runId: runData.id,
        artifactId: artifactData.id,
        version: draftVersionData.version,
        contentHash: draftVersionData.content_hash,
        brief: finalState.brief,
        draft: {
          title: finalState.brief?.topic || "Draft",
          content: draftContent,
          rationale: "Automatically generated by Maker agent"
        },
        feedback: {
          isValid: finalState.status === 'ready_for_human',
          comments: finalState.reviewFeedback ? [finalState.reviewFeedback] : [],
        },
        loopCount: finalState.revisionCount || 0
      }
    });

  } catch (error) {
    console.error('Error generating content:', error);
    return NextResponse.json(
      { error: 'Failed to generate content' },
      { status: 500 }
    );
  }
}
