import { NextResponse } from 'next/server';
import { createClient } from '@/src/infrastructure/db/server/supabase';
import { isAuthFailure, requireWorkspaceAccess } from '@/src/infrastructure/db/server/auth';

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: runId } = await params;
    const supabase = await createClient();
    const auth = await requireWorkspaceAccess(supabase);

    if (isAuthFailure(auth)) {
      return auth.response;
    }

    if (!runId) {
      return NextResponse.json({ error: 'Missing run ID' }, { status: 400 });
    }

    // Fetch the run
    const { data: run, error: runError } = await supabase
      .from('workflow_runs')
      .select('*, content_briefs(*)')
      .eq('id', runId)
      .eq('workspace_id', auth.workspaceId)
      .single();

    if (runError || !run) {
      console.error('Error fetching run:', runError);
      return NextResponse.json({ error: 'Run not found' }, { status: 404 });
    }

    // Fetch the artifact
    const { data: artifact, error: artifactError } = await supabase
      .from('content_artifacts')
      .select('*')
      .eq('workflow_run_id', runId)
      .eq('workspace_id', auth.workspaceId)
      .order('current_version', { ascending: false })
      .limit(1)
      .single();

    if (artifactError || !artifact) {
      console.error('Error fetching artifact:', artifactError);
      // We might have a run but no artifact yet
      return NextResponse.json({ error: 'Artifact not found' }, { status: 404 });
    }

    const { data: draftVersion } = await supabase
      .from('draft_versions')
      .select('version,content_hash')
      .eq('workspace_id', auth.workspaceId)
      .eq('artifact_id', artifact.id)
      .eq('version', artifact.current_version)
      .maybeSingle();

    return NextResponse.json({
      success: true,
      data: {
        briefId: run.content_briefs.id,
        runId: run.id,
        artifactId: artifact.id,
        version: draftVersion?.version ?? artifact.current_version,
        contentHash: draftVersion?.content_hash,
        brief: {
          topic: run.content_briefs.topic,
          businessGoal: run.content_briefs.business_goal,
          format: run.content_briefs.format,
          tone: run.content_briefs.angle
        },
        draft: {
          title: run.content_briefs.topic,
          content: artifact.content,
          rationale: "Automatically generated by Maker agent (loaded from DB)"
        },
        feedback: {
          isValid: run.status === 'NEEDS_HUMAN_REVIEW' || run.status === 'APPROVED',
          comments: run.status === 'NEEDS_ATTENTION' ? ["Draft needs attention according to workflow status."] : [],
        },
        loopCount: run.revision_count
      }
    });

  } catch (error) {
    console.error('Error fetching draft:', error);
    return NextResponse.json(
      { error: 'Failed to fetch draft' },
      { status: 500 }
    );
  }
}
